services:
- type: web
  name: line-bot-python-flask
  env: python
  repo: https://github.com/line/line-bot-sdk-python.git
  buildCommand: pip install gunicorn -r requirements.txt
  startCommand: gunicorn app:app
  plan: free
  autoDeploy: false
